services:
  bablobudget-services:
    build:
      context: .
      dockerfile: Dockerfile
      target: services
    ports:
      - "8018:8018" 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=${POSTGRES_DB};Username=postgres;Password=${POSTGRES_PASSWORD};"
    depends_on:
      - db
    networks:
      - bablobudgetnetwork
  
  bablobudget-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    ports:
      - "8019:8019"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=${POSTGRES_DB};Username=postgres;Password=${POSTGRES_PASSWORD};"
    depends_on:
      - bablobudget-services
    networks:
      - bablobudgetnetwork

  db:
    image: postgres:latest
    container_name: bablobudgetdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - bablobudgetnetwork
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  database:

networks:
  bablobudgetnetwork:
    driver: bridge