name: Build and Test Docker

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --target tests -t bablobudget-tests .

      - name: Run tests
        run: docker run --rm bablobudget-tests
